### ISSUE TITLE
Back-End Order Payment - No Payment Form

### ISSUE THREAD

**Issue by andrewcgregory** [digital-pros/commerce-authorize#21]
**Describe the bug**
Craft released "Back-end order editing" with [Commerce 3](https://craftcms.com/blog/commerce-3). However, when selecting using the Authorize.net payment gateway plugin no payment form shows up. Luke Holder responded in Discord that this looks like an issue with the plugin and that "if the gateway is enabled it should show up". 

**To Reproduce**
1. Go to Commerce > Orders
2. Click on **+ New Order**
3. Select Customer and Line Items
4. Select **Mark as completed**
5. Go the **Transactions** tab
6. Click **Make Payment**
7. No payment form shows up.

**Expected behavior**
Expected a payment form to display for entering credit card information.

**Screenshots**
<img width="305" alt="Payment Form" src="https://user-images.githubusercontent.com/1779776/98390785-d7b77200-2023-11eb-903a-1e68664aa0d6.png">

**Info**
Craft Pro 3.5.15.1
Craft Commerce 3.2.10.1
Authorize.net 1.0.12

**Comment by benlobach** [comment]
@andrewcgregory - Thanks for reporting this error! Do you have Accept.js toggled on in your preferences?

**Comment by andrewcgregory** [comment]
@benlobach We have Accept.js off in the settings. I did just test enabling this and still see the same issue.

**Comment by benlobach** [comment]
@andrewcgregory - Thanks for confirming, we're taking a look!

**Comment by benlobach** [comment]
@andrewcgregory - Thanks for reporting this issue! We have tracked it down, and it has been fixed in the 1.5 release that was pushed this evening. Let me know if you continue to see the problem!

**Comment by mcclaskiem** [comment]
I just updated to 1.5.1 and after trying with Accept.js turned off and on I am still not seeing the payment form. Does Commerce need to be at a certain version as well?

**Comment by benlobach** [comment]
@mcclaskiem, which version of Commerce are you running?

**Comment by mcclaskiem** [comment]
`Craft Commerce: 3.2.13.2`

**Comment by benlobach** [comment]
@mcclaskiem, perfect, thanks! Would you mind sending a screenshot of your settings to hello@digitalpros.co? (or posting a redacted version here?)

**Comment by mcclaskiem** [comment]
Email sent. Thanks!

**Comment by mcclaskiem** [comment]
@benlobach I just updated Commerce to `3.2.17.4` and the payment form now appears for Authorize.net!

**Comment by benlobach** [comment]
@mcclaskiem - Awesome, thanks for letting me know!
